# Generated by Django 4.0.6 on 2022-07-23 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='croppedimagefile',
            name='orig_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cropped_images', to='imageuploader.imagefile'),
        ),
    ]
