# Generated by Django 4.0.6 on 2022-07-24 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('singleimages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CroppedImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cropped_images')),
                ('orig_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cropped_images', to='singleimages.imagefile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cropped_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
